image:
    file: Dockerfile
#Angular CLI
tasks:
 - init: touch logs.txt  &&
         mkdir test
 - command: npm install -g npm &&
            npm install -g @angular/cli

# Ports to expose on workspace startup (optional)
ports:
  - port: 4200